FROM python:3.10.4-slim-buster

WORKDIR /server

RUN pip --no-cache-dir install gunicorn

COPY requirements.txt requirements.txt
RUN pip --no-cache-dir install -r requirements.txt

COPY app app
COPY entrypoint.sh entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
